name: Feature Request
description: Suggest a new tool or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I need to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the tool or change you'd like
      placeholder: |
        Tool name: `do_something`
        WorkBoard API endpoint: `GET /endpoint`
        Parameters: ...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?

  - type: dropdown
    id: scope
    attributes:
      label: Tool Category
      description: Which area does this feature belong to?
      options:
        - Users
        - Teams
        - Objectives
        - Key Results
        - New Category
    validations:
      required: true

  - type: dropdown
    id: workboard_api
    attributes:
      label: WorkBoard API Reference
      description: Does this correspond to an existing WorkBoard API endpoint?
      options:
        - "Yes - documented in WorkBoard API"
        - "No - new behavior / aggregation"
        - "Not sure"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information or examples
